print("str1 = this a is\tstring example....wow!!!")
print("str2 = exam")
print("str3 = this2009")
print("str4 = 23443434")
print("str5 =        ") 
print("str6 = THIS IS STRING EXAMPLE....WOW!!!")

str1=input("enter the string1 : ")
str2=input("enter the string2 : ")
str3=input("enter the string3 : ")
str4=input("enter the string4 : ")
str5=input("enter the string5 : ")
str6=input("enter the string6 : ")
intab="aeiou"
outtab="25694"
trantab=(intab,outtab)
suffix="wow!!!"
print ("endswith : ",str1.endswith(suffix))
print ("Original string: " + str1.expandtabs(16))
print ("find : ",str1.find(str2))
print ("index : ",str1.index(str2,10))
print ("isalnum : ",str3.isalnum())
print ("isalpha : ",str1.isalpha())
print ("isdigit : ",str3.isdigit())
print ("islower : ",str1.islower())
print ("isnumeric : ",str4.isnumeric())
print ("isspace : ",str5.isspace())
print ("istitle : ",str1.istitle())
print ("isupper : ",str1.isupper())
print ("Length of the string: ", len(str1))
print ("lower : ",str6.lower())
print ("istrip : ",str1.lstrip())
print ("Max character: " + max(str1))
print ("Min character: " + min(str1))
print ("replace : ",str1.replace("is","was"))
print ("rfind : ",str1.rfind(str2))
print ("rjust",str1.rjust(50,'0'))
print ("title : ",str1.title())
print ("translate : ",str1.translate(trantab))
print ("upper : ",str1.upper())
print ("zfill : ",str1.zfill(50))
print ("isdecimal : ",str4.isdecimal)